import { Info, Sparkles } from 'lucide-react';
import { cn } from '@/lib/utils';
import type { AiSource } from '@/types';

interface Props {
  source: AiSource;
  reason?: 'not-configured' | 'error';
  fallbackMethod?: string;
  className?: string;
}

/**
 * states plainly whether a result came from gemini or the offline fallback.
 *
 * showing a degraded result as though the model produced it would be
 * misleading, so this is rendered alongside every AI output.
 */
export function AiSourceNotice({ source, reason, fallbackMethod = 'a simple keyword match', className }: Props) {
  if (source === 'ai') {
    return (
      <p className={cn('flex items-center gap-1.5 text-meta text-muted-foreground', className)}>
        <Sparkles className="size-3.5 shrink-0 text-primary" aria-hidden="true" />
        Generated by AI — check anything important before relying on it.
      </p>
    );
  }

  return (
    <p
      role="status"
      className={cn(
        'flex items-start gap-2 rounded-lg border border-warning/40 bg-warning/10 px-3.5 py-2.5 text-meta',
        className
      )}
    >
      <Info className="mt-px size-3.5 shrink-0" aria-hidden="true" />
      <span>
        {reason === 'not-configured'
          ? 'The AI assistant is not configured, so these results come from '
          : 'The AI assistant is unavailable right now, so these results come from '}
        {fallbackMethod}. Everything else on this page works normally.
      </span>
    </p>
  );
}
